version: '2'

services:
  web:
    image: node:8.15.0-jessie
    build: ./
    container_name: 'node-web'
    hostname: 'dev'
    ports:
      - "80:8080"
    links:
      - database
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8080
      HOST: '0.0.0.0'
      DB_HOST: database
      DB_NAME: default
      DB_USER: default
      DB_PASS: default
      
  database:
    image: mysql:5.6
    container_name: 'mysql-db'
    volumes:
        - ./data/dump:/docker-entrypoint-initdb.d
        - ./data/db:/var/lib/mysql
    ports:
      - "3380:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
